version: '3'
services:
  db:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_PASSWORD: 1218
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data:cached
    ports:
      - 15432:5432
  app:
    build: .
    ports:
      - 18000:3000
    command: bash -c "rm -rf /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app:cached
      - /app/tmp
      - /app/log
      - /app/.git
    depends_on:
      - db
    env_file:
      - .env
    tty: true
    stdin_open: true
